### ISSUE TITLE
tangle without compiler directives?

### ISSUE THREAD

**Issue by larsks** [driusan/lmt#9]
I tried using `lmt` for documenting some shell scripts, but the generated files are splatted with what I assume are some sort of `go` compiler directives, like this:

```
%!(EXTRA int=87, main.File=2019-12-19-ovn-and-dhcp.lmt.md)#!/bin/sh

set -e

%!(EXTRA int=75, main.File=2019-12-19-ovn-and-dhcp.lmt.md)systemctl enable --now openvswitch ovn-controller
%!(EXTRA int=83, main.File=2019-12-19-ovn-and-dhcp.lmt.md)ovs-vsctl add-br br-int
```

What what I wanted was:

```
#!/bin/sh

set -e

systemctl enable --now openvswitch ovn-controller
ovs-vsctl add-br br-int
```

Is there any way to turn this off?

**Comment by driusan** [comment]
There was a bug with unknown languages when it tried adding the source line number, it should be fixed now if you update.

**Comment by larsks** [comment]
Looks good, thanks.
